# Generated by Django 4.0.4 on 2022-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='balance'),
        ),
    ]
