# Generated by Django 4.0.4 on 2022-05-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_buy_now_price_product_start_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
